
package br.com.lemontech.wsclient;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WsSelfBooking", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WsSelfBooking {


    /**
     * 
     * @param keyClient
     * @param userPassword
     * @param pesquisarSolicitacao
     * @param userName
     * @return
     *     returns br.com.lemontech.wsclient.PesquisarSolicitacaoResponse
     */
    @WebMethod
    @WebResult(name = "pesquisarSolicitacaoResponse", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", partName = "pesquisarSolicitacaoResponse")
    @Action(input = "http://lemontech.com.br/selfbooking/wsselfbooking/services/WsSelfBooking/pesquisarSolicitacaoRequest", output = "http://lemontech.com.br/selfbooking/wsselfbooking/services/WsSelfBooking/pesquisarSolicitacaoResponse")
    public PesquisarSolicitacaoResponse pesquisarSolicitacao(
        @WebParam(name = "keyClient", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true, partName = "keyClient")
        String keyClient,
        @WebParam(name = "userName", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true, partName = "userName")
        String userName,
        @WebParam(name = "userPassword", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true, partName = "userPassword")
        String userPassword,
        @WebParam(name = "pesquisarSolicitacao", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", partName = "pesquisarSolicitacao")
        PesquisarSolicitacaoRequest pesquisarSolicitacao);

    /**
     * 
     * @param keyClient
     * @param userPassword
     * @param sincronizarSolicitacao
     * @param userName
     * @return
     *     returns br.com.lemontech.wsclient.SincronizarSolicitacaoResponse
     */
    @WebMethod
    @WebResult(name = "sincronizarSolicitacaoResponse", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", partName = "sincronizarSolicitacaoResponse")
    @Action(input = "http://lemontech.com.br/selfbooking/wsselfbooking/services/WsSelfBooking/sincronizarSolicitacaoRequest", output = "http://lemontech.com.br/selfbooking/wsselfbooking/services/WsSelfBooking/sincronizarSolicitacaoResponse")
    public SincronizarSolicitacaoResponse sincronizarSolicitacao(
        @WebParam(name = "keyClient", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true, partName = "keyClient")
        String keyClient,
        @WebParam(name = "userName", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true, partName = "userName")
        String userName,
        @WebParam(name = "userPassword", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true, partName = "userPassword")
        String userPassword,
        @WebParam(name = "sincronizarSolicitacao", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", partName = "sincronizarSolicitacao")
        SincronizarSolicitacaoRequest sincronizarSolicitacao);

    /**
     * 
     * @param keyClient
     * @param userPassword
     * @param userName
     * @param cadastrarRegional
     * @return
     *     returns br.com.lemontech.wsclient.CadastrarRegionalResponse
     */
    @WebMethod
    @WebResult(name = "cadastrarRegionalResponse", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", partName = "cadastrarRegionalResponse")
    @Action(input = "http://lemontech.com.br/selfbooking/wsselfbooking/services/WsSelfBooking/cadastrarRegionalRequest", output = "http://lemontech.com.br/selfbooking/wsselfbooking/services/WsSelfBooking/cadastrarRegionalResponse")
    public CadastrarRegionalResponse cadastrarRegional(
        @WebParam(name = "keyClient", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true, partName = "keyClient")
        String keyClient,
        @WebParam(name = "userName", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true, partName = "userName")
        String userName,
        @WebParam(name = "userPassword", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true, partName = "userPassword")
        String userPassword,
        @WebParam(name = "cadastrarRegional", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", partName = "cadastrarRegional")
        CadastrarRegionalRequest cadastrarRegional);

    /**
     * 
     * @param keyClient
     * @param alterarStatusRegional
     * @param userPassword
     * @param userName
     * @return
     *     returns br.com.lemontech.wsclient.AlterarStatusRegionalResponse
     */
    @WebMethod
    @WebResult(name = "alterarStatusRegionalResponse", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", partName = "alterarStatusRegionalResponse")
    @Action(input = "http://lemontech.com.br/selfbooking/fornecedores/services/WsFornecedores/alterarStatusRegionalRequest", output = "http://lemontech.com.br/selfbooking/fornecedores/services/WsFornecedores/alterarStatusRegionalResponse")
    public AlterarStatusRegionalResponse alterarStatusRegional(
        @WebParam(name = "keyClient", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true, partName = "keyClient")
        String keyClient,
        @WebParam(name = "userName", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true, partName = "userName")
        String userName,
        @WebParam(name = "userPassword", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true, partName = "userPassword")
        String userPassword,
        @WebParam(name = "alterarStatusRegional", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", partName = "alterarStatusRegional")
        AlterarStatusRegionalRequest alterarStatusRegional);

    /**
     * 
     * @param keyClient
     * @param userPassword
     * @param userName
     * @param cadastrarContaContabil
     * @return
     *     returns br.com.lemontech.wsclient.CadastrarContaContabilResponse
     */
    @WebMethod
    @WebResult(name = "cadastrarContaContabilResponse", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", partName = "cadastrarContaContabilResponse")
    @Action(input = "http://lemontech.com.br/selfbooking/wsselfbooking/services/WsSelfBooking/cadastrarContaContabilRequest", output = "http://lemontech.com.br/selfbooking/wsselfbooking/services/WsSelfBooking/cadastrarContaContabilResponse")
    public CadastrarContaContabilResponse cadastrarContaContabil(
        @WebParam(name = "keyClient", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true, partName = "keyClient")
        String keyClient,
        @WebParam(name = "userName", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true, partName = "userName")
        String userName,
        @WebParam(name = "userPassword", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true, partName = "userPassword")
        String userPassword,
        @WebParam(name = "cadastrarContaContabil", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", partName = "cadastrarContaContabil")
        CadastrarContaContabilRequest cadastrarContaContabil);

    /**
     * 
     * @param keyClient
     * @param alterarStatusContaContabil
     * @param userPassword
     * @param userName
     * @return
     *     returns br.com.lemontech.wsclient.AlterarStatusContaContabilResponse
     */
    @WebMethod
    @WebResult(name = "alterarStatusContaContabilResponse", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", partName = "alterarStatusContaContabilResponse")
    @Action(input = "http://lemontech.com.br/selfbooking/fornecedores/services/WsFornecedores/alterarStatusContaContabilRequest", output = "http://lemontech.com.br/selfbooking/fornecedores/services/WsFornecedores/alterarStatusContaContabilResponse")
    public AlterarStatusContaContabilResponse alterarStatusContaContabil(
        @WebParam(name = "keyClient", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true, partName = "keyClient")
        String keyClient,
        @WebParam(name = "userName", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true, partName = "userName")
        String userName,
        @WebParam(name = "userPassword", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true, partName = "userPassword")
        String userPassword,
        @WebParam(name = "alterarStatusContaContabil", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", partName = "alterarStatusContaContabil")
        AlterarStatusContaContabilRequest alterarStatusContaContabil);

    /**
     * 
     * @param keyClient
     * @param userPassword
     * @param userName
     * @param cadastrarCentroDeCusto
     * @return
     *     returns br.com.lemontech.wsclient.CadastrarCentroDeCustoResponse
     */
    @WebMethod
    @WebResult(name = "cadastrarCentroDeCustoResponse", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", partName = "cadastrarCentroDeCustoResponse")
    @Action(input = "http://lemontech.com.br/selfbooking/wsselfbooking/services/WsSelfBooking/cadastrarCentroDeCustoRequest", output = "http://lemontech.com.br/selfbooking/wsselfbooking/services/WsSelfBooking/cadastrarCentroDeCustoResponse")
    public CadastrarCentroDeCustoResponse cadastrarCentroDeCusto(
        @WebParam(name = "keyClient", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true, partName = "keyClient")
        String keyClient,
        @WebParam(name = "userName", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true, partName = "userName")
        String userName,
        @WebParam(name = "userPassword", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true, partName = "userPassword")
        String userPassword,
        @WebParam(name = "cadastrarCentroDeCusto", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", partName = "cadastrarCentroDeCusto")
        CadastrarCentroDeCustoRequest cadastrarCentroDeCusto);

    /**
     * 
     * @param keyClient
     * @param userPassword
     * @param alterarStatusCentroDeCusto
     * @param userName
     * @return
     *     returns br.com.lemontech.wsclient.AlterarStatusCentroDeCustoResponse
     */
    @WebMethod
    @WebResult(name = "alterarStatusCentroDeCustoResponse", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", partName = "alterarStatusCentroDeCustoResponse")
    @Action(input = "http://lemontech.com.br/selfbooking/fornecedores/services/WsFornecedores/alterarStatusCentroDeCustoRequest", output = "http://lemontech.com.br/selfbooking/fornecedores/services/WsFornecedores/alterarStatusCentroDeCustoResponse")
    public AlterarStatusCentroDeCustoResponse alterarStatusCentroDeCusto(
        @WebParam(name = "keyClient", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true, partName = "keyClient")
        String keyClient,
        @WebParam(name = "userName", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true, partName = "userName")
        String userName,
        @WebParam(name = "userPassword", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true, partName = "userPassword")
        String userPassword,
        @WebParam(name = "alterarStatusCentroDeCusto", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", partName = "alterarStatusCentroDeCusto")
        AlterarStatusCentroDeCustoRequest alterarStatusCentroDeCusto);

    /**
     * 
     * @param keyClient
     * @param userPassword
     * @param userName
     * @param cadastrarSubCentroDeCusto
     * @return
     *     returns br.com.lemontech.wsclient.CadastrarSubCentroDeCustoResponse
     */
    @WebMethod
    @WebResult(name = "cadastrarSubCentroDeCustoResponse", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", partName = "cadastrarSubCentroDeCustoResponse")
    @Action(input = "http://lemontech.com.br/selfbooking/wsselfbooking/services/WsSelfBooking/cadastrarSubCentroDeCustoRequest", output = "http://lemontech.com.br/selfbooking/wsselfbooking/services/WsSelfBooking/cadastrarSubCentroDeCustoResponse")
    public CadastrarSubCentroDeCustoResponse cadastrarSubCentroDeCusto(
        @WebParam(name = "keyClient", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true, partName = "keyClient")
        String keyClient,
        @WebParam(name = "userName", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true, partName = "userName")
        String userName,
        @WebParam(name = "userPassword", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true, partName = "userPassword")
        String userPassword,
        @WebParam(name = "cadastrarSubCentroDeCusto", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", partName = "cadastrarSubCentroDeCusto")
        CadastrarSubCentroDeCustoRequest cadastrarSubCentroDeCusto);

    /**
     * 
     * @param keyClient
     * @param userPassword
     * @param alterarStatusSubCentroDeCusto
     * @param userName
     * @return
     *     returns br.com.lemontech.wsclient.AlterarStatusSubCentroDeCustoResponse
     */
    @WebMethod
    @WebResult(name = "alterarStatusSubCentroDeCustoResponse", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", partName = "alterarStatusSubCentroDeCustoResponse")
    @Action(input = "http://lemontech.com.br/selfbooking/fornecedores/services/WsFornecedores/alterarStatusSubCentroDeCustoRequest", output = "http://lemontech.com.br/selfbooking/fornecedores/services/WsFornecedores/alterarStatusSubCentroDeCustoResponse")
    public AlterarStatusSubCentroDeCustoResponse alterarStatusSubCentroDeCusto(
        @WebParam(name = "keyClient", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true, partName = "keyClient")
        String keyClient,
        @WebParam(name = "userName", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true, partName = "userName")
        String userName,
        @WebParam(name = "userPassword", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true, partName = "userPassword")
        String userPassword,
        @WebParam(name = "alterarStatusSubCentroDeCusto", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", partName = "alterarStatusSubCentroDeCusto")
        AlterarStatusSubCentroDeCustoRequest alterarStatusSubCentroDeCusto);

    /**
     * 
     * @param keyClient
     * @param userPassword
     * @param userName
     * @param cadastrarParametrizacaoCentroDeCusto
     * @return
     *     returns br.com.lemontech.wsclient.CadastrarParametrizacaoCentroDeCustoResponse
     */
    @WebMethod
    @WebResult(name = "cadastrarParametrizacaoCentroDeCustoResponse", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", partName = "cadastrarParametrizacaoCentroDeCustoResponse")
    @Action(input = "http://lemontech.com.br/selfbooking/wsselfbooking/services/WsSelfBooking/cadastrarParametrizacaoCentroDeCustoRequest", output = "http://lemontech.com.br/selfbooking/wsselfbooking/services/WsSelfBooking/cadastrarParametrizacaoCentroDeCustoResponse")
    public CadastrarParametrizacaoCentroDeCustoResponse cadastrarParametrizacaoCentroDeCusto(
        @WebParam(name = "keyClient", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true, partName = "keyClient")
        String keyClient,
        @WebParam(name = "userName", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true, partName = "userName")
        String userName,
        @WebParam(name = "userPassword", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true, partName = "userPassword")
        String userPassword,
        @WebParam(name = "cadastrarParametrizacaoCentroDeCusto", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", partName = "cadastrarParametrizacaoCentroDeCusto")
        CadastrarParametrizacaoCentroDeCustoRequest cadastrarParametrizacaoCentroDeCusto);

    /**
     * 
     * @param keyClient
     * @param deletarParametrizacaoCentroDeCusto
     * @param userPassword
     * @param userName
     * @return
     *     returns br.com.lemontech.wsclient.DeletarParametrizacaoCentroDeCustoResponse
     */
    @WebMethod
    @WebResult(name = "deletarParametrizacaoCentroDeCustoResponse", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", partName = "deletarParametrizacaoCentroDeCustoResponse")
    @Action(input = "http://lemontech.com.br/selfbooking/wsselfbooking/services/WsSelfBooking/deletarParametrizacaoCentroDeCustoRequest", output = "http://lemontech.com.br/selfbooking/wsselfbooking/services/WsSelfBooking/deletarParametrizacaoCentroDeCustoResponse")
    public DeletarParametrizacaoCentroDeCustoResponse deletarParametrizacaoCentroDeCusto(
        @WebParam(name = "keyClient", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true, partName = "keyClient")
        String keyClient,
        @WebParam(name = "userName", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true, partName = "userName")
        String userName,
        @WebParam(name = "userPassword", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true, partName = "userPassword")
        String userPassword,
        @WebParam(name = "deletarParametrizacaoCentroDeCusto", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", partName = "deletarParametrizacaoCentroDeCusto")
        DeletarParametrizacaoCentroDeCustoRequest deletarParametrizacaoCentroDeCusto);

    /**
     * 
     * @param keyClient
     * @param userPassword
     * @param cadastrarFuncionario
     * @param userName
     * @return
     *     returns br.com.lemontech.wsclient.CadastrarFuncionarioResponse
     */
    @WebMethod
    @WebResult(name = "cadastrarFuncionarioResponse", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", partName = "cadastrarFuncionarioResponse")
    @Action(input = "http://lemontech.com.br/selfbooking/wsselfbooking/services/WsSelfBooking/cadastrarFuncionarioRequest", output = "http://lemontech.com.br/selfbooking/wsselfbooking/services/WsSelfBooking/cadastrarFuncionarioResponse")
    public CadastrarFuncionarioResponse cadastrarFuncionario(
        @WebParam(name = "keyClient", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true, partName = "keyClient")
        String keyClient,
        @WebParam(name = "userName", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true, partName = "userName")
        String userName,
        @WebParam(name = "userPassword", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true, partName = "userPassword")
        String userPassword,
        @WebParam(name = "cadastrarFuncionario", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", partName = "cadastrarFuncionario")
        CadastrarFuncionarioRequest cadastrarFuncionario);

    /**
     * 
     * @param keyClient
     * @param pesquisarFuncionario
     * @param userPassword
     * @param userName
     * @return
     *     returns br.com.lemontech.wsclient.PesquisarFuncionarioResponse
     */
    @WebMethod
    @WebResult(name = "pesquisarFuncionarioResponse", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", partName = "pesquisarFuncionarioResponse")
    @Action(input = "http://lemontech.com.br/selfbooking/wsselfbooking/services/WsSelfBooking/pesquisarFuncionarioRequest", output = "http://lemontech.com.br/selfbooking/wsselfbooking/services/WsSelfBooking/pesquisarFuncionarioResponse")
    public PesquisarFuncionarioResponse pesquisarFuncionario(
        @WebParam(name = "keyClient", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true, partName = "keyClient")
        String keyClient,
        @WebParam(name = "userName", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true, partName = "userName")
        String userName,
        @WebParam(name = "userPassword", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true, partName = "userPassword")
        String userPassword,
        @WebParam(name = "pesquisarFuncionario", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", partName = "pesquisarFuncionario")
        PesquisarFuncionarioRequest pesquisarFuncionario);

    /**
     * 
     * @param keyClient
     * @param alterarStatusFuncionario
     * @param userPassword
     * @param userName
     * @return
     *     returns br.com.lemontech.wsclient.AlterarStatusFuncionarioResponse
     */
    @WebMethod
    @WebResult(name = "alterarStatusFuncionarioResponse", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", partName = "alterarStatusFuncionarioResponse")
    @Action(input = "http://lemontech.com.br/selfbooking/fornecedores/services/WsFornecedores/alterarStatusFuncionarioRequest", output = "http://lemontech.com.br/selfbooking/fornecedores/services/WsFornecedores/alterarStatusFuncionarioResponse")
    public AlterarStatusFuncionarioResponse alterarStatusFuncionario(
        @WebParam(name = "keyClient", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true, partName = "keyClient")
        String keyClient,
        @WebParam(name = "userName", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true, partName = "userName")
        String userName,
        @WebParam(name = "userPassword", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true, partName = "userPassword")
        String userPassword,
        @WebParam(name = "alterarStatusFuncionario", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", partName = "alterarStatusFuncionario")
        AlterarStatusFuncionarioRequest alterarStatusFuncionario);

    /**
     * 
     * @param keyClient
     * @param userPassword
     * @param cadastrarFornecedor
     * @param userName
     * @return
     *     returns br.com.lemontech.wsclient.CadastrarFornecedorResponse
     */
    @WebMethod
    @WebResult(name = "cadastrarFornecedorResponse", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", partName = "cadastrarFornecedorResponse")
    @Action(input = "http://lemontech.com.br/selfbooking/fornecedores/services/WsFornecedores/cadastrarFornecedorRequest", output = "http://lemontech.com.br/selfbooking/fornecedores/services/WsFornecedores/cadastrarFornecedorResponse")
    public CadastrarFornecedorResponse cadastrarFornecedor(
        @WebParam(name = "keyClient", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true, partName = "keyClient")
        String keyClient,
        @WebParam(name = "userName", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true, partName = "userName")
        String userName,
        @WebParam(name = "userPassword", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true, partName = "userPassword")
        String userPassword,
        @WebParam(name = "cadastrarFornecedor", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", partName = "cadastrarFornecedor")
        CadastrarFornecedorRequest cadastrarFornecedor);

    /**
     * 
     * @param keyClient
     * @param userPassword
     * @param alterarStatusFornecedor
     * @param userName
     * @return
     *     returns br.com.lemontech.wsclient.AlterarStatusFornecedorResponse
     */
    @WebMethod
    @WebResult(name = "alterarStatusFornecedorResponse", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", partName = "alterarStatusFornecedorResponse")
    @Action(input = "http://lemontech.com.br/selfbooking/fornecedores/services/WsFornecedores/alterarStatusFornecedorRequest", output = "http://lemontech.com.br/selfbooking/fornecedores/services/WsFornecedores/alterarStatusFornecedorResponse")
    public AlterarStatusFornecedorResponse alterarStatusFornecedor(
        @WebParam(name = "keyClient", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true, partName = "keyClient")
        String keyClient,
        @WebParam(name = "userName", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true, partName = "userName")
        String userName,
        @WebParam(name = "userPassword", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true, partName = "userPassword")
        String userPassword,
        @WebParam(name = "alterarStatusFornecedor", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", partName = "alterarStatusFornecedor")
        AlterarStatusFornecedorRequest alterarStatusFornecedor);

    /**
     * 
     * @param keyClient
     * @param cadastrarTarifario
     * @param userPassword
     * @param userName
     * @return
     *     returns br.com.lemontech.wsclient.CadastrarTarifarioResponse
     */
    @WebMethod
    @WebResult(name = "cadastrarTarifarioResponse", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", partName = "cadastrarTarifarioResponse")
    @Action(input = "http://lemontech.com.br/selfbooking/fornecedores/services/WsFornecedores/cadastrarTarifarioRequest", output = "http://lemontech.com.br/selfbooking/fornecedores/services/WsFornecedores/cadastrarTarifarioResponse")
    public CadastrarTarifarioResponse cadastrarTarifario(
        @WebParam(name = "keyClient", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true, partName = "keyClient")
        String keyClient,
        @WebParam(name = "userName", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true, partName = "userName")
        String userName,
        @WebParam(name = "userPassword", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true, partName = "userPassword")
        String userPassword,
        @WebParam(name = "cadastrarTarifario", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", partName = "cadastrarTarifario")
        CadastrarTarifarioRequest cadastrarTarifario);

    /**
     * 
     * @param keyClient
     * @param userPassword
     * @param alterarStatusTarifario
     * @param userName
     * @return
     *     returns br.com.lemontech.wsclient.AlterarStatusTarifarioResponse
     */
    @WebMethod
    @WebResult(name = "alterarStatusTarifarioResponse", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", partName = "alterarStatusTarifarioResponse")
    @Action(input = "http://lemontech.com.br/selfbooking/fornecedores/services/WsFornecedores/alterarStatusTarifarioRequest", output = "http://lemontech.com.br/selfbooking/fornecedores/services/WsFornecedores/alterarStatusTarifarioResponse")
    public AlterarStatusTarifarioResponse alterarStatusTarifario(
        @WebParam(name = "keyClient", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true, partName = "keyClient")
        String keyClient,
        @WebParam(name = "userName", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true, partName = "userName")
        String userName,
        @WebParam(name = "userPassword", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true, partName = "userPassword")
        String userPassword,
        @WebParam(name = "alterarStatusTarifario", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", partName = "alterarStatusTarifario")
        AlterarStatusTarifarioRequest alterarStatusTarifario);

    /**
     * 
     * @param keyClient
     * @param userPassword
     * @param aprovarSolicitacao
     * @param userName
     * @return
     *     returns br.com.lemontech.wsclient.AprovarSolicitacaoResponse
     */
    @WebMethod
    @WebResult(name = "aprovarSolicitacaoResponse", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", partName = "aprovarSolicitacaoResponse")
    @Action(input = "http://lemontech.com.br/selfbooking/fornecedores/services/WsSelfBooking/aprovarSolicitacaoRequest", output = "http://lemontech.com.br/selfbooking/fornecedores/services/WsSelfBooking/aprovarSolicitacaoResponse")
    public AprovarSolicitacaoResponse aprovarSolicitacao(
        @WebParam(name = "keyClient", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true, partName = "keyClient")
        String keyClient,
        @WebParam(name = "userName", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true, partName = "userName")
        String userName,
        @WebParam(name = "userPassword", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true, partName = "userPassword")
        String userPassword,
        @WebParam(name = "aprovarSolicitacao", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", partName = "aprovarSolicitacao")
        AprovarSolicitacaoRequest aprovarSolicitacao);

    /**
     * 
     * @param keyClient
     * @param userPassword
     * @param reprovarSolicitacao
     * @param userName
     * @return
     *     returns br.com.lemontech.wsclient.ReprovarSolicitacaoResponse
     */
    @WebMethod
    @WebResult(name = "reprovarSolicitacaoResponse", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", partName = "reprovarSolicitacaoResponse")
    @Action(input = "http://lemontech.com.br/selfbooking/fornecedores/services/WsSelfBooking/reprovarSolicitacaoRequest", output = "http://lemontech.com.br/selfbooking/fornecedores/services/WsSelfBooking/reprovarSolicitacaoResponse")
    public ReprovarSolicitacaoResponse reprovarSolicitacao(
        @WebParam(name = "keyClient", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true, partName = "keyClient")
        String keyClient,
        @WebParam(name = "userName", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true, partName = "userName")
        String userName,
        @WebParam(name = "userPassword", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true, partName = "userPassword")
        String userPassword,
        @WebParam(name = "reprovarSolicitacao", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", partName = "reprovarSolicitacao")
        ReprovarSolicitacaoRequest reprovarSolicitacao);

    /**
     * 
     * @param keyClient
     * @param userPassword
     * @param inserirIdentificadorIntegracao
     * @param userName
     * @return
     *     returns br.com.lemontech.wsclient.InserirIdentificadorIntegracaoResponse
     */
    @WebMethod
    @WebResult(name = "inserirIdentificadorIntegracaoResponse", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", partName = "inserirIdentificadorIntegracaoResponse")
    @Action(input = "http://lemontech.com.br/selfbooking/fornecedores/services/WsSelfBooking/inserirIdentificadorIntegracaoRequest", output = "http://lemontech.com.br/selfbooking/fornecedores/services/WsSelfBooking/inserirIdentificadorIntegracaoResponse")
    public InserirIdentificadorIntegracaoResponse inserirIdentificadorIntegracao(
        @WebParam(name = "keyClient", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true, partName = "keyClient")
        String keyClient,
        @WebParam(name = "userName", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true, partName = "userName")
        String userName,
        @WebParam(name = "userPassword", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true, partName = "userPassword")
        String userPassword,
        @WebParam(name = "inserirIdentificadorIntegracao", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", partName = "inserirIdentificadorIntegracao")
        InserirIdentificadorIntegracaoRequest inserirIdentificadorIntegracao);

    /**
     * 
     * @param keyClient
     * @param userPassword
     * @param userName
     * @param cadastrarParametrizacaoViajante
     * @return
     *     returns br.com.lemontech.wsclient.CadastrarParametrizacaoViajanteResponse
     */
    @WebMethod
    @WebResult(name = "cadastrarParametrizacaoViajanteResponse", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", partName = "cadastrarParametrizacaoViajanteResponse")
    @Action(input = "http://lemontech.com.br/selfbooking/wsselfbooking/services/WsSelfBooking/cadastrarParametrizacaoViajanteRequest", output = "http://lemontech.com.br/selfbooking/wsselfbooking/services/WsSelfBooking/cadastrarParametrizacaoViajanteResponse")
    public CadastrarParametrizacaoViajanteResponse cadastrarParametrizacaoViajante(
        @WebParam(name = "keyClient", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true, partName = "keyClient")
        String keyClient,
        @WebParam(name = "userName", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true, partName = "userName")
        String userName,
        @WebParam(name = "userPassword", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true, partName = "userPassword")
        String userPassword,
        @WebParam(name = "cadastrarParametrizacaoViajante", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", partName = "cadastrarParametrizacaoViajante")
        CadastrarParametrizacaoViajanteRequest cadastrarParametrizacaoViajante);

    /**
     * 
     * @param keyClient
     * @param userPassword
     * @param deletarParametrizacaoViajante
     * @param userName
     * @return
     *     returns br.com.lemontech.wsclient.DeletarParametrizacaoViajanteResponse
     */
    @WebMethod
    @WebResult(name = "deletarParametrizacaoViajanteResponse", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", partName = "deletarParametrizacaoViajanteResponse")
    @Action(input = "http://lemontech.com.br/selfbooking/wsselfbooking/services/WsSelfBooking/deletarParametrizacaoViajanteRequest", output = "http://lemontech.com.br/selfbooking/wsselfbooking/services/WsSelfBooking/deletarParametrizacaoViajanteResponse")
    public DeletarParametrizacaoViajanteResponse deletarParametrizacaoViajante(
        @WebParam(name = "keyClient", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true, partName = "keyClient")
        String keyClient,
        @WebParam(name = "userName", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true, partName = "userName")
        String userName,
        @WebParam(name = "userPassword", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true, partName = "userPassword")
        String userPassword,
        @WebParam(name = "deletarParametrizacaoViajante", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", partName = "deletarParametrizacaoViajante")
        DeletarParametrizacaoViajanteRequest deletarParametrizacaoViajante);

    /**
     * 
     * @param keyClient
     * @param userPassword
     * @param pesquisarVendasConsolidadora
     * @param userName
     * @return
     *     returns br.com.lemontech.wsclient.PesquisarVendasConsolidadoraResponse
     */
    @WebMethod
    @WebResult(name = "pesquisarVendasConsolidadoraResponse", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", partName = "pesquisarVendasConsolidadoraResponse")
    @Action(input = "http://lemontech.com.br/selfbooking/wsselfbooking/services/WsSelfBooking/pesquisarVendasConsolidadoraRequest", output = "http://lemontech.com.br/selfbooking/wsselfbooking/services/WsSelfBooking/pesquisarVendasConsolidadoraResponse")
    public PesquisarVendasConsolidadoraResponse pesquisarVendasConsolidadora(
        @WebParam(name = "keyClient", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true, partName = "keyClient")
        String keyClient,
        @WebParam(name = "userName", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true, partName = "userName")
        String userName,
        @WebParam(name = "userPassword", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true, partName = "userPassword")
        String userPassword,
        @WebParam(name = "pesquisarVendasConsolidadora", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", partName = "pesquisarVendasConsolidadora")
        PesquisarVendasConsolidadoraRequest pesquisarVendasConsolidadora);

    /**
     * 
     * @param keyClient
     * @param cadastrarFornecedorSource
     * @param userPassword
     * @param userName
     * @return
     *     returns br.com.lemontech.wsclient.CadastrarFornecedorSourceResponse
     */
    @WebMethod
    @WebResult(name = "cadastrarFornecedorSourceResponse", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", partName = "cadastrarFornecedorSourceResponse")
    @Action(input = "http://lemontech.com.br/selfbooking/fornecedores/services/WsFornecedores/cadastrarFornecedorSourceRequest", output = "http://lemontech.com.br/selfbooking/fornecedores/services/WsFornecedores/cadastrarFornecedorSourceResponse")
    public CadastrarFornecedorSourceResponse cadastrarFornecedorSource(
        @WebParam(name = "keyClient", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true, partName = "keyClient")
        String keyClient,
        @WebParam(name = "userName", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true, partName = "userName")
        String userName,
        @WebParam(name = "userPassword", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true, partName = "userPassword")
        String userPassword,
        @WebParam(name = "cadastrarFornecedorSource", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", partName = "cadastrarFornecedorSource")
        CadastrarFornecedorSourceRequest cadastrarFornecedorSource);

    /**
     * 
     * @param keyClient
     * @param userPassword
     * @param userName
     * @param inserirItemDespesa
     * @return
     *     returns br.com.lemontech.wsclient.InserirItemDespesaResponse
     */
    @WebMethod
    @WebResult(name = "inserirItemDespesaResponse", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", partName = "inserirItemDespesaResponse")
    @Action(input = "http://lemontech.com.br/selfbooking/fornecedores/services/WsSelfBooking/inserirItemDespesaRequest", output = "http://lemontech.com.br/selfbooking/fornecedores/services/WsSelfBooking/inserirItemDespesaResponse")
    public InserirItemDespesaResponse inserirItemDespesa(
        @WebParam(name = "keyClient", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true, partName = "keyClient")
        String keyClient,
        @WebParam(name = "userName", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true, partName = "userName")
        String userName,
        @WebParam(name = "userPassword", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true, partName = "userPassword")
        String userPassword,
        @WebParam(name = "inserirItemDespesa", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", partName = "inserirItemDespesa")
        InserirItemDespesaRequest inserirItemDespesa);

    /**
     * 
     * @param keyClient
     * @param userPassword
     * @param userName
     * @param cadastrarProjeto
     * @return
     *     returns br.com.lemontech.wsclient.CadastrarProjetoResponse
     */
    @WebMethod
    @WebResult(name = "cadastrarProjetoResponse", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", partName = "cadastrarProjetoResponse")
    @Action(input = "http://lemontech.com.br/selfbooking/wsselfbooking/services/WsSelfBooking/cadastrarProjetoRequest", output = "http://lemontech.com.br/selfbooking/wsselfbooking/services/WsSelfBooking/cadastrarProjetoResponse")
    public CadastrarProjetoResponse cadastrarProjeto(
        @WebParam(name = "keyClient", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true, partName = "keyClient")
        String keyClient,
        @WebParam(name = "userName", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true, partName = "userName")
        String userName,
        @WebParam(name = "userPassword", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true, partName = "userPassword")
        String userPassword,
        @WebParam(name = "cadastrarProjeto", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", partName = "cadastrarProjeto")
        CadastrarProjetoRequest cadastrarProjeto);

    /**
     * 
     * @param keyClient
     * @param userPassword
     * @param alterarStatusProjeto
     * @param userName
     * @return
     *     returns br.com.lemontech.wsclient.AlterarStatusProjetoResponse
     */
    @WebMethod
    @WebResult(name = "alterarStatusProjetoResponse", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", partName = "alterarStatusProjetoResponse")
    @Action(input = "http://lemontech.com.br/selfbooking/wsselfbooking/services/WsSelfBooking//alterarStatusProjetoRequest", output = "http://lemontech.com.br/selfbooking/wsselfbooking/services/WsSelfBooking/alterarStatusProjetoResponse")
    public AlterarStatusProjetoResponse alterarStatusProjeto(
        @WebParam(name = "keyClient", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true, partName = "keyClient")
        String keyClient,
        @WebParam(name = "userName", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true, partName = "userName")
        String userName,
        @WebParam(name = "userPassword", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true, partName = "userPassword")
        String userPassword,
        @WebParam(name = "alterarStatusProjeto", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", partName = "alterarStatusProjeto")
        AlterarStatusProjetoRequest alterarStatusProjeto);

    /**
     * 
     * @param keyClient
     * @param userPassword
     * @param atualizarBudget
     * @param userName
     * @return
     *     returns br.com.lemontech.wsclient.AtualizarBudgetResponse
     */
    @WebMethod
    @WebResult(name = "atualizarBudgetResponse", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", partName = "atualizarBudgetResponse")
    @Action(input = "http://lemontech.com.br/selfbooking/wsselfbooking/services/WsSelfBooking/atualizarBudgetRequest", output = "http://lemontech.com.br/selfbooking/wsselfbooking/services/WsSelfBooking/atualizarBudgetResponse")
    public AtualizarBudgetResponse atualizarBudget(
        @WebParam(name = "keyClient", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true, partName = "keyClient")
        String keyClient,
        @WebParam(name = "userName", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true, partName = "userName")
        String userName,
        @WebParam(name = "userPassword", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true, partName = "userPassword")
        String userPassword,
        @WebParam(name = "atualizarBudget", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", partName = "atualizarBudget")
        AtualizarBudgetRequest atualizarBudget);

    /**
     * 
     * @param keyClient
     * @param consultaBilheteCia
     * @param userPassword
     * @param userName
     * @return
     *     returns br.com.lemontech.wsclient.ConsultaBilheteCiaResponse
     */
    @WebMethod
    @WebResult(name = "consultaBilheteCiaResponse", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", partName = "consultaBilheteCiaResponse")
    @Action(input = "http://lemontech.com.br/selfbooking/wsselfbooking/services/WsSelfBooking/consultaBilheteCiaRequest", output = "http://lemontech.com.br/selfbooking/wsselfbooking/services/WsSelfBooking/consultaBilheteCiaResponse")
    public ConsultaBilheteCiaResponse consultaBilheteCia(
        @WebParam(name = "keyClient", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true, partName = "keyClient")
        String keyClient,
        @WebParam(name = "userName", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true, partName = "userName")
        String userName,
        @WebParam(name = "userPassword", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true, partName = "userPassword")
        String userPassword,
        @WebParam(name = "consultaBilheteCia", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", partName = "consultaBilheteCia")
        ConsultaBilheteCiaRequest consultaBilheteCia);

    /**
     * 
     * @param keyClient
     * @param cadastrarHoteisHomologados
     * @param userPassword
     * @param userName
     * @return
     *     returns br.com.lemontech.wsclient.CadastrarHoteisHomologadosResponse
     */
    @WebMethod
    @WebResult(name = "cadastrarHoteisHomologadosResponse", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", partName = "cadastrarHoteisHomologadosResponse")
    @Action(input = "http://lemontech.com.br/selfbooking/wsselfbooking/services/WsSelfBooking/cadastrarHoteisHomologadosRequest", output = "http://lemontech.com.br/selfbooking/wsselfbooking/services/WsSelfBooking/cadastrarHoteisHomologadosResponse")
    public CadastrarHoteisHomologadosResponse cadastrarHoteisHomologados(
        @WebParam(name = "keyClient", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true, partName = "keyClient")
        String keyClient,
        @WebParam(name = "userName", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true, partName = "userName")
        String userName,
        @WebParam(name = "userPassword", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true, partName = "userPassword")
        String userPassword,
        @WebParam(name = "cadastrarHoteisHomologados", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", partName = "cadastrarHoteisHomologados")
        CadastrarHoteisHomologadosRequest cadastrarHoteisHomologados);

    /**
     * 
     * @param keyClient
     * @param userPassword
     * @param atrelarUsuarios
     * @param userName
     * @return
     *     returns br.com.lemontech.wsclient.AtrelarUsuariosResponse
     */
    @WebMethod
    @WebResult(name = "atrelarUsuariosResponse", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", partName = "atrelarUsuariosResponse")
    @Action(input = "http://lemontech.com.br/selfbooking/fornecedores/services/WsFornecedores/atrelarUsuariosRequest", output = "http://lemontech.com.br/selfbooking/fornecedores/services/WsFornecedores/atrelarUsuariosResponse")
    public AtrelarUsuariosResponse atrelarUsuarios(
        @WebParam(name = "keyClient", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true, partName = "keyClient")
        String keyClient,
        @WebParam(name = "userName", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true, partName = "userName")
        String userName,
        @WebParam(name = "userPassword", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true, partName = "userPassword")
        String userPassword,
        @WebParam(name = "atrelarUsuarios", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", partName = "atrelarUsuarios")
        AtrelarUsuariosRequest atrelarUsuarios);

    /**
     * 
     * @param keyClient
     * @param userPassword
     * @param userName
     * @param finalizarSolicitacao
     * @return
     *     returns br.com.lemontech.wsclient.FinalizarSolicitacaoResponse
     */
    @WebMethod
    @WebResult(name = "finalizarSolicitacaoResponse", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", partName = "finalizarSolicitacaoResponse")
    @Action(input = "http://lemontech.com.br/selfbooking/wsselfbooking/services/WsSelfBooking/finalizarSolicitacaoRequest", output = "http://lemontech.com.br/selfbooking/wsselfbooking/services/WsSelfBooking/finalizarSolicitacaoResponse")
    public FinalizarSolicitacaoResponse finalizarSolicitacao(
        @WebParam(name = "keyClient", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true, partName = "keyClient")
        String keyClient,
        @WebParam(name = "userName", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true, partName = "userName")
        String userName,
        @WebParam(name = "userPassword", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true, partName = "userPassword")
        String userPassword,
        @WebParam(name = "finalizarSolicitacao", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", partName = "finalizarSolicitacao")
        FinalizarSolicitacaoRequest finalizarSolicitacao);

    /**
     * 
     * @param keyClient
     * @param userPassword
     * @param cadastrarTreinamento
     * @param userName
     * @return
     *     returns br.com.lemontech.wsclient.CadastrarTreinamentoResponse
     */
    @WebMethod
    @WebResult(name = "cadastrarTreinamentoResponse", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", partName = "cadastrarTreinamentoResponse")
    @Action(input = "http://lemontech.com.br/selfbooking/wsselfbooking/services/WsSelfBooking/cadastrarTreinamentoRequest", output = "http://lemontech.com.br/selfbooking/wsselfbooking/services/WsSelfBooking/cadastrarTreinamentoResponse")
    public CadastrarTreinamentoResponse cadastrarTreinamento(
        @WebParam(name = "keyClient", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true, partName = "keyClient")
        String keyClient,
        @WebParam(name = "userName", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true, partName = "userName")
        String userName,
        @WebParam(name = "userPassword", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true, partName = "userPassword")
        String userPassword,
        @WebParam(name = "cadastrarTreinamento", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", partName = "cadastrarTreinamento")
        CadastrarTreinamentoRequest cadastrarTreinamento);

    /**
     * 
     * @param keyClient
     * @param userPassword
     * @param cadastrarParticipanteTreinamento
     * @param userName
     * @return
     *     returns br.com.lemontech.wsclient.CadastrarParticipanteTreinamentoResponse
     */
    @WebMethod
    @WebResult(name = "cadastrarParticipanteTreinamentoResponse", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", partName = "cadastrarParticipanteTreinamentoResponse")
    @Action(input = "http://lemontech.com.br/selfbooking/wsselfbooking/services/WsSelfBooking/cadastrarParticipanteTreinamentoRequest", output = "http://lemontech.com.br/selfbooking/wsselfbooking/services/WsSelfBooking/cadastrarParticipanteTreinamentoResponse")
    public CadastrarParticipanteTreinamentoResponse cadastrarParticipanteTreinamento(
        @WebParam(name = "keyClient", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true, partName = "keyClient")
        String keyClient,
        @WebParam(name = "userName", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true, partName = "userName")
        String userName,
        @WebParam(name = "userPassword", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true, partName = "userPassword")
        String userPassword,
        @WebParam(name = "cadastrarParticipanteTreinamento", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", partName = "cadastrarParticipanteTreinamento")
        CadastrarParticipanteTreinamentoRequest cadastrarParticipanteTreinamento);

    /**
     * 
     * @param keyClient
     * @param userPassword
     * @param deletarTreinamento
     * @param userName
     * @return
     *     returns br.com.lemontech.wsclient.DeletarTreinamentoResponse
     */
    @WebMethod
    @WebResult(name = "deletarTreinamentoResponse", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", partName = "deletarTreinamentoResponse")
    @Action(input = "http://lemontech.com.br/selfbooking/wsselfbooking/services/WsSelfBooking/deletarTreinamentoRequest", output = "http://lemontech.com.br/selfbooking/wsselfbooking/services/WsSelfBooking/deletarTreinamentoResponse")
    public DeletarTreinamentoResponse deletarTreinamento(
        @WebParam(name = "keyClient", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true, partName = "keyClient")
        String keyClient,
        @WebParam(name = "userName", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true, partName = "userName")
        String userName,
        @WebParam(name = "userPassword", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true, partName = "userPassword")
        String userPassword,
        @WebParam(name = "deletarTreinamento", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", partName = "deletarTreinamento")
        DeletarTreinamentoRequest deletarTreinamento);

    /**
     * 
     * @param keyClient
     * @param userPassword
     * @param deletarParticipanteTreinamento
     * @param userName
     * @return
     *     returns br.com.lemontech.wsclient.DeletarParticipanteTreinamentoResponse
     */
    @WebMethod
    @WebResult(name = "deletarParticipanteTreinamentoResponse", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", partName = "deletarParticipanteTreinamentoResponse")
    @Action(input = "http://lemontech.com.br/selfbooking/wsselfbooking/services/WsSelfBooking/deletarParticipanteTreinamentoRequest", output = "http://lemontech.com.br/selfbooking/wsselfbooking/services/WsSelfBooking/deletarParticipanteTreinamentoResponse")
    public DeletarParticipanteTreinamentoResponse deletarParticipanteTreinamento(
        @WebParam(name = "keyClient", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true, partName = "keyClient")
        String keyClient,
        @WebParam(name = "userName", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true, partName = "userName")
        String userName,
        @WebParam(name = "userPassword", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true, partName = "userPassword")
        String userPassword,
        @WebParam(name = "deletarParticipanteTreinamento", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", partName = "deletarParticipanteTreinamento")
        DeletarParticipanteTreinamentoRequest deletarParticipanteTreinamento);

    /**
     * 
     * @param keyClient
     * @param criarPreSolicitacao
     * @param userPassword
     * @param userName
     * @return
     *     returns br.com.lemontech.wsclient.CriarPreSolicitacaoResponse
     */
    @WebMethod
    @WebResult(name = "criarPreSolicitacaoResponse", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", partName = "criarPreSolicitacaoResponse")
    @Action(input = "http://lemontech.com.br/selfbooking/wsselfbooking/services/WsSelfBooking/criarPreSolicitacaoRequest", output = "http://lemontech.com.br/selfbooking/wsselfbooking/services/WsSelfBooking/criarPreSolicitacaoResponse")
    public CriarPreSolicitacaoResponse criarPreSolicitacao(
        @WebParam(name = "keyClient", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true, partName = "keyClient")
        String keyClient,
        @WebParam(name = "userName", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true, partName = "userName")
        String userName,
        @WebParam(name = "userPassword", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true, partName = "userPassword")
        String userPassword,
        @WebParam(name = "criarPreSolicitacao", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", partName = "criarPreSolicitacao")
        CriarPreSolicitacaoRequest criarPreSolicitacao);

    /**
     * 
     * @param keyClient
     * @param contaBancaria
     * @param userPassword
     * @param userName
     * @return
     *     returns br.com.lemontech.wsclient.ContaBancariaResponse
     */
    @WebMethod
    @WebResult(name = "contaBancariaResponse", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", partName = "contaBancariaResponse")
    @Action(input = "http://lemontech.com.br/selfbooking/wsselfbooking/services/WsSelfBooking/contaBancariaRequest", output = "http://lemontech.com.br/selfbooking/wsselfbooking/services/WsSelfBooking/contaBancariaResponse")
    public ContaBancariaResponse contaBancaria(
        @WebParam(name = "keyClient", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true, partName = "keyClient")
        String keyClient,
        @WebParam(name = "userName", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true, partName = "userName")
        String userName,
        @WebParam(name = "userPassword", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true, partName = "userPassword")
        String userPassword,
        @WebParam(name = "contaBancaria", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", partName = "contaBancaria")
        ContaBancariaRequest contaBancaria);

    /**
     * 
     * @param keyClient
     * @param userPassword
     * @param importarDelegacaoParametrizacaoCentroDeCusto
     * @param userName
     * @return
     *     returns br.com.lemontech.wsclient.ImportarDelegacaoParametrizacaoCentroDeCustoResponse
     */
    @WebMethod
    @WebResult(name = "importarDelegacaoParametrizacaoCentroDeCustoResponse", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", partName = "importarDelegacaoParametrizacaoCentroDeCustoResponse")
    @Action(input = "http://lemontech.com.br/selfbooking/wsselfbooking/services/WsSelfBooking/importarDelegacaoParametrizacaoCentroDeCustoRequest", output = "http://lemontech.com.br/selfbooking/wsselfbooking/services/WsSelfBooking/importarDelegacaoParametrizacaoCentroDeCustoResponse")
    public ImportarDelegacaoParametrizacaoCentroDeCustoResponse importarDelegacaoParametrizacaoCentroDeCusto(
        @WebParam(name = "keyClient", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true, partName = "keyClient")
        String keyClient,
        @WebParam(name = "userName", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true, partName = "userName")
        String userName,
        @WebParam(name = "userPassword", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true, partName = "userPassword")
        String userPassword,
        @WebParam(name = "importarDelegacaoParametrizacaoCentroDeCusto", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", partName = "importarDelegacaoParametrizacaoCentroDeCusto")
        ImportarDelegacaoParametrizacaoCentroDeCustoRequest importarDelegacaoParametrizacaoCentroDeCusto);

    /**
     * 
     * @param keyClient
     * @param userPassword
     * @param cadastrarControleCliente
     * @param userName
     * @return
     *     returns br.com.lemontech.wsclient.CadastrarControleClienteResponse
     */
    @WebMethod
    @WebResult(name = "cadastrarControleClienteResponse", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", partName = "cadastrarControleClienteResponse")
    @Action(input = "http://lemontech.com.br/selfbooking/wsselfbooking/services/WsSelfBooking/cadastrarControleClienteRequest", output = "http://lemontech.com.br/selfbooking/wsselfbooking/services/WsSelfBooking/cadastrarControleClienteResponse")
    public CadastrarControleClienteResponse cadastrarControleCliente(
        @WebParam(name = "keyClient", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true, partName = "keyClient")
        String keyClient,
        @WebParam(name = "userName", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true, partName = "userName")
        String userName,
        @WebParam(name = "userPassword", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true, partName = "userPassword")
        String userPassword,
        @WebParam(name = "cadastrarControleCliente", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", partName = "cadastrarControleCliente")
        CadastrarControleClienteRequest cadastrarControleCliente);

    /**
     * 
     * @param keyClient
     * @param userPassword
     * @param cadastrarUnidadeNegocio
     * @param userName
     * @return
     *     returns br.com.lemontech.wsclient.CadastrarUnidadeNegocioResponse
     */
    @WebMethod
    @WebResult(name = "cadastrarUnidadeNegocioResponse", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", partName = "cadastrarUnidadeNegocioResponse")
    @Action(input = "http://lemontech.com.br/selfbooking/wsselfbooking/services/WsSelfBooking/cadastrarUnidadeNegocioRequest", output = "http://lemontech.com.br/selfbooking/wsselfbooking/services/WsSelfBooking/cadastrarUnidadeNegocioResponse")
    public CadastrarUnidadeNegocioResponse cadastrarUnidadeNegocio(
        @WebParam(name = "keyClient", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true, partName = "keyClient")
        String keyClient,
        @WebParam(name = "userName", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true, partName = "userName")
        String userName,
        @WebParam(name = "userPassword", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true, partName = "userPassword")
        String userPassword,
        @WebParam(name = "cadastrarUnidadeNegocio", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", partName = "cadastrarUnidadeNegocio")
        CadastrarUnidadeNegocioRequest cadastrarUnidadeNegocio);

    /**
     * 
     * @param keyClient
     * @param userPassword
     * @param importarFaturaCartaoCredito
     * @param userName
     * @return
     *     returns br.com.lemontech.wsclient.ImportarFaturaCartaoCreditoResponse
     */
    @WebMethod
    @WebResult(name = "importarFaturaCartaoCreditoResponse", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", partName = "importarFaturaCartaoCreditoResponse")
    @Action(input = "http://lemontech.com.br/selfbooking/wsselfbooking/services/WsSelfBooking/importarFaturaCartaoCreditoRequest", output = "http://lemontech.com.br/selfbooking/wsselfbooking/services/WsSelfBooking/importarFaturaCartaoCreditoResponse")
    public ImportarFaturaCartaoCreditoResponse importarFaturaCartaoCredito(
        @WebParam(name = "keyClient", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true, partName = "keyClient")
        String keyClient,
        @WebParam(name = "userName", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true, partName = "userName")
        String userName,
        @WebParam(name = "userPassword", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true, partName = "userPassword")
        String userPassword,
        @WebParam(name = "importarFaturaCartaoCredito", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", partName = "importarFaturaCartaoCredito")
        ImportarFaturaCartaoCreditoRequest importarFaturaCartaoCredito);

    /**
     * 
     * @param keyClient
     * @param userPassword
     * @param pesquisarAdiantamento
     * @param userName
     * @return
     *     returns br.com.lemontech.wsclient.PesquisarAdiantamentoResponse
     */
    @WebMethod
    @WebResult(name = "pesquisarAdiantamentoResponse", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", partName = "pesquisarAdiantamentoResponse")
    @Action(input = "http://lemontech.com.br/selfbooking/wsselfbooking/services/WsSelfBooking/pesquisarAdiantamentoRequest", output = "http://lemontech.com.br/selfbooking/wsselfbooking/services/WsSelfBooking/pesquisarAdiantamentoResponse")
    public PesquisarAdiantamentoResponse pesquisarAdiantamento(
        @WebParam(name = "keyClient", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true, partName = "keyClient")
        String keyClient,
        @WebParam(name = "userName", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true, partName = "userName")
        String userName,
        @WebParam(name = "userPassword", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true, partName = "userPassword")
        String userPassword,
        @WebParam(name = "pesquisarAdiantamento", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", partName = "pesquisarAdiantamento")
        PesquisarAdiantamentoRequest pesquisarAdiantamento);

    /**
     * 
     * @param keyClient
     * @param userPassword
     * @param pesquisarRelatorioDespesas
     * @param userName
     * @return
     *     returns br.com.lemontech.wsclient.PesquisarRelatorioDespesasResponse
     */
    @WebMethod
    @WebResult(name = "pesquisarRelatorioDespesasResponse", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", partName = "pesquisarRelatorioDespesasResponse")
    @Action(input = "http://lemontech.com.br/selfbooking/wsselfbooking/services/WsSelfBooking/pesquisarRelatorioDespesasRequest", output = "http://lemontech.com.br/selfbooking/wsselfbooking/services/WsSelfBooking/pesquisarRelatorioDespesasResponse")
    public PesquisarRelatorioDespesasResponse pesquisarRelatorioDespesas(
        @WebParam(name = "keyClient", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true, partName = "keyClient")
        String keyClient,
        @WebParam(name = "userName", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true, partName = "userName")
        String userName,
        @WebParam(name = "userPassword", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true, partName = "userPassword")
        String userPassword,
        @WebParam(name = "pesquisarRelatorioDespesas", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", partName = "pesquisarRelatorioDespesas")
        PesquisarRelatorioDespesasRequest pesquisarRelatorioDespesas);

    /**
     * 
     * @param keyClient
     * @param userPassword
     * @param importarDespesa
     * @param userName
     * @return
     *     returns br.com.lemontech.wsclient.ImportarDespesaResponse
     */
    @WebMethod
    @WebResult(name = "importarDespesaResponse", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", partName = "importarDespesaResponse")
    @Action(input = "http://lemontech.com.br/selfbooking/wsselfbooking/services/WsSelfBooking/importarDespesaRequest", output = "http://lemontech.com.br/selfbooking/wsselfbooking/services/WsSelfBooking/importarDespesaResponse")
    public ImportarDespesaResponse importarDespesa(
        @WebParam(name = "keyClient", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true, partName = "keyClient")
        String keyClient,
        @WebParam(name = "userName", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true, partName = "userName")
        String userName,
        @WebParam(name = "userPassword", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true, partName = "userPassword")
        String userPassword,
        @WebParam(name = "importarDespesa", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", partName = "importarDespesa")
        ImportarDespesaRequest importarDespesa);

    /**
     * 
     * @param keyClient
     * @param userPassword
     * @param userName
     * @param liberarAdiantamento
     * @return
     *     returns br.com.lemontech.wsclient.LiberarAdiantamentoResponse
     */
    @WebMethod
    @WebResult(name = "liberarAdiantamentoResponse", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", partName = "liberarAdiantamentoResponse")
    @Action(input = "http://lemontech.com.br/selfbooking/wsselfbooking/services/WsSelfBooking/liberarAdiantamentoRequest", output = "http://lemontech.com.br/selfbooking/wsselfbooking/services/WsSelfBooking/liberarAdiantamentoResponse")
    public LiberarAdiantamentoResponse liberarAdiantamento(
        @WebParam(name = "keyClient", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true, partName = "keyClient")
        String keyClient,
        @WebParam(name = "userName", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true, partName = "userName")
        String userName,
        @WebParam(name = "userPassword", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true, partName = "userPassword")
        String userPassword,
        @WebParam(name = "liberarAdiantamento", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", partName = "liberarAdiantamento")
        LiberarAdiantamentoRequest liberarAdiantamento);

    /**
     * 
     * @param keyClient
     * @param userPassword
     * @param userName
     * @param contabilizarRelatorioDespesas
     * @return
     *     returns br.com.lemontech.wsclient.ContabilizarRelatorioDespesasResponse
     */
    @WebMethod
    @WebResult(name = "contabilizarRelatorioDespesasResponse", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", partName = "contabilizarRelatorioDespesasResponse")
    @Action(input = "http://lemontech.com.br/selfbooking/wsselfbooking/services/WsSelfBooking/contabilizarRelatorioDespesasRequest", output = "http://lemontech.com.br/selfbooking/wsselfbooking/services/WsSelfBooking/contabilizarRelatorioDespesasResponse")
    public ContabilizarRelatorioDespesasResponse contabilizarRelatorioDespesas(
        @WebParam(name = "keyClient", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true, partName = "keyClient")
        String keyClient,
        @WebParam(name = "userName", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true, partName = "userName")
        String userName,
        @WebParam(name = "userPassword", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true, partName = "userPassword")
        String userPassword,
        @WebParam(name = "contabilizarRelatorioDespesas", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", partName = "contabilizarRelatorioDespesas")
        ContabilizarRelatorioDespesasRequest contabilizarRelatorioDespesas);

    /**
     * 
     * @param keyClient
     * @param userPassword
     * @param pesquisarLogsAcesso
     * @param userName
     * @return
     *     returns br.com.lemontech.wsclient.PesquisarLogsAcessoResponse
     */
    @WebMethod
    @WebResult(name = "pesquisarLogsAcessoResponse", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", partName = "pesquisarLogsAcessoResponse")
    @Action(input = "http://lemontech.com.br/selfbooking/wsselfbooking/services/WsSelfBooking/pesquisarLogsAcessoRequest", output = "http://lemontech.com.br/selfbooking/wsselfbooking/services/WsSelfBooking/pesquisarLogsAcessoResponse")
    public PesquisarLogsAcessoResponse pesquisarLogsAcesso(
        @WebParam(name = "keyClient", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true, partName = "keyClient")
        String keyClient,
        @WebParam(name = "userName", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true, partName = "userName")
        String userName,
        @WebParam(name = "userPassword", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true, partName = "userPassword")
        String userPassword,
        @WebParam(name = "pesquisarLogsAcesso", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", partName = "pesquisarLogsAcesso")
        PesquisarLogsAcessoRequest pesquisarLogsAcesso);

    /**
     * 
     * @param keyClient
     * @param listarCentroDeCusto
     * @param userPassword
     * @param userName
     * @return
     *     returns br.com.lemontech.wsclient.ListarCentroDeCustoResponse
     */
    @WebMethod
    @WebResult(name = "listarCentroDeCustoResponse", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", partName = "listarCentroDeCustoResponse")
    @Action(input = "http://lemontech.com.br/selfbooking/fornecedores/services/WsFornecedores/listarCentroDeCustoRequest", output = "http://lemontech.com.br/selfbooking/fornecedores/services/WsFornecedores/listarCentroDeCustoResponse")
    public ListarCentroDeCustoResponse listarCentroDeCusto(
        @WebParam(name = "keyClient", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true, partName = "keyClient")
        String keyClient,
        @WebParam(name = "userName", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true, partName = "userName")
        String userName,
        @WebParam(name = "userPassword", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true, partName = "userPassword")
        String userPassword,
        @WebParam(name = "listarCentroDeCusto", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", partName = "listarCentroDeCusto")
        ListarCentroDeCustoRequest listarCentroDeCusto);

    /**
     * 
     * @param keyClient
     * @param listarSubCentroDeCusto
     * @param userPassword
     * @param userName
     * @return
     *     returns br.com.lemontech.wsclient.ListarSubCentroDeCustoResponse
     */
    @WebMethod
    @WebResult(name = "listarSubCentroDeCustoResponse", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", partName = "listarSubCentroDeCustoResponse")
    @Action(input = "http://lemontech.com.br/selfbooking/fornecedores/services/WsFornecedores/listarSubCentroDeCustoRequest", output = "http://lemontech.com.br/selfbooking/fornecedores/services/WsFornecedores/listarSubCentroDeCustoResponse")
    public ListarSubCentroDeCustoResponse listarSubCentroDeCusto(
        @WebParam(name = "keyClient", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true, partName = "keyClient")
        String keyClient,
        @WebParam(name = "userName", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true, partName = "userName")
        String userName,
        @WebParam(name = "userPassword", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true, partName = "userPassword")
        String userPassword,
        @WebParam(name = "listarSubCentroDeCusto", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", partName = "listarSubCentroDeCusto")
        ListarSubCentroDeCustoRequest listarSubCentroDeCusto);

    /**
     * 
     * @param keyClient
     * @param userPassword
     * @param userName
     * @param listarParametrizacaoCentroDeCusto
     * @return
     *     returns br.com.lemontech.wsclient.ListarParametrizacaoCentroDeCustoResponse
     */
    @WebMethod
    @WebResult(name = "listarParametrizacaoCentroDeCustoResponse", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", partName = "listarParametrizacaoCentroDeCustoResponse")
    @Action(input = "http://lemontech.com.br/selfbooking/fornecedores/services/WsFornecedores/listarParametrizacaoCentroDeCustoRequest", output = "http://lemontech.com.br/selfbooking/fornecedores/services/WsFornecedores/listarParametrizacaoCentroDeCustoResponse")
    public ListarParametrizacaoCentroDeCustoResponse listarParametrizacaoCentroDeCusto(
        @WebParam(name = "keyClient", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true, partName = "keyClient")
        String keyClient,
        @WebParam(name = "userName", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true, partName = "userName")
        String userName,
        @WebParam(name = "userPassword", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true, partName = "userPassword")
        String userPassword,
        @WebParam(name = "listarParametrizacaoCentroDeCusto", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", partName = "listarParametrizacaoCentroDeCusto")
        ListarParametrizacaoCentroDeCustoRequest listarParametrizacaoCentroDeCusto);

    /**
     * 
     * @param keyClient
     * @param userPassword
     * @param pesquisarConciliacaoCartao
     * @param userName
     * @return
     *     returns br.com.lemontech.wsclient.PesquisarConciliacaoCartaoResponse
     */
    @WebMethod
    @WebResult(name = "pesquisarConciliacaoCartaoResponse", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", partName = "pesquisarConciliacaoCartaoResponse")
    @Action(input = "http://lemontech.com.br/selfbooking/wsselfbooking/services/WsSelfBooking/pesquisarConciliacaoCartaoRequest", output = "http://lemontech.com.br/selfbooking/wsselfbooking/services/WsSelfBooking/pesquisarConciliacaoCartaoResponse")
    public PesquisarConciliacaoCartaoResponse pesquisarConciliacaoCartao(
        @WebParam(name = "keyClient", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true, partName = "keyClient")
        String keyClient,
        @WebParam(name = "userName", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true, partName = "userName")
        String userName,
        @WebParam(name = "userPassword", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true, partName = "userPassword")
        String userPassword,
        @WebParam(name = "pesquisarConciliacaoCartao", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", partName = "pesquisarConciliacaoCartao")
        PesquisarConciliacaoCartaoRequest pesquisarConciliacaoCartao);

    /**
     * 
     * @param keyClient
     * @param userPassword
     * @param cancelarSolicitacao
     * @param userName
     * @return
     *     returns br.com.lemontech.wsclient.CancelarSolicitacaoResponse
     */
    @WebMethod
    @WebResult(name = "cancelarSolicitacaoResponse", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", partName = "cancelarSolicitacaoResponse")
    @Action(input = "http://lemontech.com.br/selfbooking/wsselfbooking/services/WsSelfBooking/cancelarSolicitacaoRequest", output = "http://lemontech.com.br/selfbooking/wsselfbooking/services/WsSelfBooking/cancelarSolicitacaoResponse")
    public CancelarSolicitacaoResponse cancelarSolicitacao(
        @WebParam(name = "keyClient", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true, partName = "keyClient")
        String keyClient,
        @WebParam(name = "userName", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true, partName = "userName")
        String userName,
        @WebParam(name = "userPassword", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true, partName = "userPassword")
        String userPassword,
        @WebParam(name = "cancelarSolicitacao", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", partName = "cancelarSolicitacao")
        CancelarSolicitacaoRequest cancelarSolicitacao);

    /**
     * 
     * @param keyClient
     * @param userPassword
     * @param ping
     * @param userName
     * @return
     *     returns br.com.lemontech.wsclient.PingResponse
     */
    @WebMethod
    @WebResult(name = "pingResponse", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", partName = "pingResponse")
    @Action(input = "http://lemontech.com.br/selfbooking/wsselfbooking/services/WsSelfBooking/pingRequest", output = "http://lemontech.com.br/selfbooking/wsselfbooking/services/WsSelfBooking/pingResponse")
    public PingResponse ping(
        @WebParam(name = "keyClient", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true, partName = "keyClient")
        String keyClient,
        @WebParam(name = "userName", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true, partName = "userName")
        String userName,
        @WebParam(name = "userPassword", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true, partName = "userPassword")
        String userPassword,
        @WebParam(name = "ping", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", partName = "ping")
        PingRequest ping);

    /**
     * 
     * @param keyClient
     * @param userPassword
     * @param pesquisarContaBancaria
     * @param userName
     * @return
     *     returns br.com.lemontech.wsclient.PesquisarContaBancariaResponse
     */
    @WebMethod
    @WebResult(name = "pesquisarContaBancariaResponse", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", partName = "pesquisarContaBancariaResponse")
    @Action(input = "http://lemontech.com.br/selfbooking/wsselfbooking/services/WsSelfBooking/pesquisarContaBancariaRequest", output = "http://lemontech.com.br/selfbooking/wsselfbooking/services/WsSelfBooking/pesquisarContaBancariaResponse")
    public PesquisarContaBancariaResponse pesquisarContaBancaria(
        @WebParam(name = "keyClient", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true, partName = "keyClient")
        String keyClient,
        @WebParam(name = "userName", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true, partName = "userName")
        String userName,
        @WebParam(name = "userPassword", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true, partName = "userPassword")
        String userPassword,
        @WebParam(name = "pesquisarContaBancaria", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", partName = "pesquisarContaBancaria")
        PesquisarContaBancariaRequest pesquisarContaBancaria);

}
